const test = require("node:test");
const assert = require("node:assert/strict");
const { createChatTelemetry } = require("../../src/chat/chatTelemetry.cjs");

test("createChatTelemetry aggregates counters", () => {
  const t = createChatTelemetry();
  t.recordRequest();
  t.recordGuardrailBlock();
  t.recordModeUsage("rag");
  t.recordModeUsage("llm");
  t.recordRequestLatencyMs(12.5);
  t.recordRequestLatencyMs(7.5);
  t.recordResponseCacheHit();
  t.recordResponseCacheMiss();
  t.recordEmbedCacheHit();
  t.recordEmbedCacheMiss();
  t.recordRetrievalCacheHit();
  t.recordRetrievalCacheMiss();
  t.recordBudgetBlock();
  t.recordLlmRetry();
  t.recordCircuitOpen();
  t.recordCircuitRejection();
  t.recordLlmInvocation({ prompt_tokens: 1, completion_tokens: 2, total_tokens: 3 }, 0.001);
  const s = t.snapshot();
  assert.equal(s.requests_total, 1);
  assert.equal(s.guardrail_blocks, 1);
  assert.equal(s.mode_rag_total, 1);
  assert.equal(s.mode_llm_total, 1);
  assert.equal(s.request_latency_ms_count, 2);
  assert.equal(s.request_latency_ms_sum, 20);
  assert.equal(s.request_latency_ms_max, 12.5);
  assert.equal(s.response_cache_hits, 1);
  assert.equal(s.response_cache_misses, 1);
  assert.equal(s.embed_cache_hits, 1);
  assert.equal(s.embed_cache_misses, 1);
  assert.equal(s.retrieval_cache_hits, 1);
  assert.equal(s.retrieval_cache_misses, 1);
  assert.equal(s.budget_blocks, 1);
  assert.equal(s.llm_retries, 1);
  assert.equal(s.circuit_opens, 1);
  assert.equal(s.circuit_rejections, 1);
  assert.equal(s.llm_invocations, 1);
  assert.equal(s.total_prompt_tokens, 1);
  assert.equal(s.total_completion_tokens, 2);
  assert.ok(s.estimated_cost_usd_total > 0);
});
